#!/bin/bash

# Deal with macports/git splitting out the git-prompt utils into their own file
if [ -f /opt/local/share/git-core/git-prompt.sh ]; then
      . /opt/local/share/git-core/git-prompt.sh
fi

# Add these if bash_completion is running
if [[ $EUID > 0 && "`type -t __git_ps1`" == 'function' ]]; then
    export GIT_PS1_SHOWDIRTYSTATE=true
    export GIT_PS1_SHOWUNTRACKEDFILES=true
    export PS1="${FG_BLUE}\u${FG_CYAN}@${FGBLUE}\h${ANSI_RESET}: ${FG_GREEN}\w ${FG_DARKGRAY}\$(__git_ps1 '(%s) ')${FG_DARKGRAY}>${ANSI_RESET} "

fi

#
# Git aliases
#

  alias gitlog='git log --decorate --name-status'
  alias gg='git grep'

#
# opens the current branch on github.com.  Would call this "github" but it conflicts with github's own CLI app to open their desktop app
#

  git_hub() {
    BRANCH=`git rev-parse --symbolic-full-name --abbrev-ref @{u} 2>/dev/null`
    if [[ $? != 0 ]]; then
      echo "Not currently in a git repository"
      return
    fi
    if [[ -z $BRANCH ]]; then
      echo "Can't determine current git branch name"
      return
    fi
    IFS_STORE="$IFS"
    IFS=$'\n'
    for REMOTE in `git remote`; do
        if [[ $BRANCH == "$REMOTE/"* ]]; then
          SHORT_BRANCH=${BRANCH#$REMOTE/}
          GITHUB_REPO=`git remote show "$REMOTE" | grep 'Fetch URL' | awk -F: '{ print $3 }' | sed -e 's,.git$,,'`
          if [[ $? != 0 ]]; then
            echo "Error loading github project info"
            break
          fi
          if [[ -z $BRANCH ]]; then
            echo "Couldn't determine github project info"
            break
          fi
          if [[ $SHORT_BRANCH == 'master' ]]; then
            # todo `git br -a | grep HEAD | ....`
            URL="https://github.com/$GITHUB_REPO/"
          else
            URL="https://github.com/$GITHUB_REPO/tree/$SHORT_BRANCH"
          fi
          echo "$URL"
          if [[ `uname` == 'Darwin' ]]; then
            open "$URL"
          elif `which xdg-open >/dev/null`; then
            xdg-open "$URL"
          else
            echo "Couldn't find URL opener"
          fi
          break
        fi
    done
    IFS="$IFS_STORE"
  }

#
# git_cleanup is intended to be attached to a git alias.
# It will remove any remote (origin) branches that have already been merged into
# master, and have remained untouched for at least a month.
#
# Credit to https://github.com/cxreg
#
  git_cleanup() {
    for branch in $(git branch -r --merged origin/master | grep '\<origin/' | grep -v '\<origin/master\>'); do
      if [[ -z $(git rev-list $branch --since='1 month') ]]; then
        name=$(echo $branch | sed 's/^origin\///')
          echo git push --delete origin "$name"
      fi
    done
  }
  export -f git_cleanup

#
# git_only intended to be attached to a git alias.
# Given a branch name, it will show you a log of commits that only exist on that one branch.
#
# Credit to https://github.com/cxreg
#
  function git_only() {
    opts=$(git rev-parse --no-revs "$@" 2>/dev/null)
    rev=$(git rev-parse --revs-only "$@" 2>/dev/null)
    if [[ -z $rev ]]; then
      branch=$(git name-rev --name-only HEAD)
    else
      branch=$rev
    fi
    git log $(git rev-parse --not --remotes --branches | grep -v $(git rev-parse $branch)) $branch $opts
  }
  export -f git_only

#
# Install our functions.  These do not auto-run because they are only needed once,
# and in case users want to apply them only to a specific git clone.
#
#  git config --global alias.only '!git_only'
#  git config --global alias.cleanup '!git_cleanup'

# git config --global http.sslVerify false
# git config --global merge.tool vimdiff

