#!/bin/bash

# Add these if bash_completion is running
if [[ "`type -t __git_ps1`" -eq 'function' ]]; then
    export GIT_PS1_SHOWDIRTYSTATE=true
    export GIT_PS1_SHOWUNTRACKEDFILES=true

    export PS1="${FG_BLUE}\u${FG_CYAN}@${FGBLUE}\h${ANSI_RESET}: ${FG_GREEN}\w ${FG_DARKGRAY}\$(__git_ps1 '(%s) ')${FG_DARKGRAY}>${ANSI_RESET} "

fi

#
# Git aliases
#

  alias gitlog='git log --decorate --name-status'
  alias gg='git grep'


#
#
#
  git_cleanup() {
    for branch in $(git branch -r --merged origin/master | grep '\<origin/' | grep -v '\<origin/master\>'); do
      if [[ -z $(git rev-list $branch --since='1 month') ]]; then
        name=$(echo $branch | sed 's/^origin\///')
          echo git push --delete origin "$name"
      fi
    done
  }

